//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Launcher.Plugin.Dictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flow.Launcher.Plugin.Dictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Audio acquisition failure 的本地化字符串。
        /// </summary>
        public static string AudioFailure {
            get {
                return ResourceManager.GetString("AudioFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Token 的本地化字符串。
        /// </summary>
        public static string AudioToken {
            get {
                return ResourceManager.GetString("AudioToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bighugelabs Token 的本地化字符串。
        /// </summary>
        public static string BighugelabsToken {
            get {
                return ResourceManager.GetString("BighugelabsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Definition 的本地化字符串。
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary database not found (~1GB Decompressed) 的本地化字符串。
        /// </summary>
        public static string DictionaryDes {
            get {
                return ResourceManager.GetString("DictionaryDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading dictionary database... 的本地化字符串。
        /// </summary>
        public static string DownloadingDB {
            get {
                return ResourceManager.GetString("DownloadingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press enter to download to 的本地化字符串。
        /// </summary>
        public static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exchanges 的本地化字符串。
        /// </summary>
        public static string Exchanges {
            get {
                return ResourceManager.GetString("Exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ICIBA Token 的本地化字符串。
        /// </summary>
        public static string ICIBAToken {
            get {
                return ResourceManager.GetString("ICIBAToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max spelling correction distance 的本地化字符串。
        /// </summary>
        public static string MaxCorrection {
            get {
                return ResourceManager.GetString("MaxCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Results Found 的本地化字符串。
        /// </summary>
        public static string NoFound {
            get {
                return ResourceManager.GetString("NoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phonetic 的本地化字符串。
        /// </summary>
        public static string Phonetic {
            get {
                return ResourceManager.GetString("Phonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press enter to refresh precentage. 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English dictionary and word correction. 的本地化字符串。
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synonym 的本地化字符串。
        /// </summary>
        public static string Synonym {
            get {
                return ResourceManager.GetString("Synonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation 的本地化字符串。
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word 的本地化字符串。
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
