//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Launcher.Plugin.VisualStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flow.Launcher.Plugin.VisualStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Workspaces 的本地化字符串。
        /// </summary>
        public static string CustomWorkspaces {
            get {
                return ResourceManager.GetString("CustomWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Visual Studio 的本地化字符串。
        /// </summary>
        public static string DefaultVisualStudio {
            get {
                return ResourceManager.GetString("DefaultVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude Workspaces 的本地化字符串。
        /// </summary>
        public static string ExcludeCustomWorkspaces {
            get {
                return ResourceManager.GetString("ExcludeCustomWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open your recent solutions in Visual Studio 的本地化字符串。
        /// </summary>
        public static string PlugSubTitle {
            get {
                return ResourceManager.GetString("PlugSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Studio Launcher 的本地化字符串。
        /// </summary>
        public static string PlugTitle {
            get {
                return ResourceManager.GetString("PlugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Visual Studio Instances 的本地化字符串。
        /// </summary>
        public static string ReloadVisualStudioInstances {
            get {
                return ResourceManager.GetString("ReloadVisualStudioInstances", resourceCulture);
            }
        }
    }
}
